<?php

/**
 * @file
 * Webform SP Privacy webform component.
 */

/**
 * Implements hook_webform_component_info().
 */
function sp_privacy_webform_component_info() {
  $components = array();

  $components['sp_privacy'] = array(
    'label' => 'SP privacy formulier element',
    'description' => 'Voegt een formulier element toe waarmee relaties hun privacy voorkeuren kunnen aangegeven.',
    'features' => array(
      'analysis' => FALSE,
      'csv' => TRUE,
      'required' => TRUE,
      'sp_privacy' => TRUE,
      'conditional' => TRUE,
      'title_display' => TRUE,
      'title_inline' => TRUE,
      'private' => FALSE,
      'group' => FALSE,
      'spam_analysis' => FALSE,
      'attachment' => FALSE,
    ),
  );

  return $components;
}

/**
 * Implements _webform_defaults_component().
 */
function _webform_defaults_sp_privacy() {
  return array(
    'name' => '',
    'form_key' => NULL,
    'required' => FALSE,
    'pid' => 0,
    'weight' => 0,
    'extra' => array(
      'key' => '',
      'secret' => '',
      'private' => FALSE,
    ),
  );
}

/**
 * Implements _webform_edit_component().
 */
function _webform_edit_sp_privacy($component) {
  $form = array();

  return $form;
}

/**
 * Implements _webform_render_component().
 */
function _webform_render_sp_privacy($component) {
  // Wrap the form in a container, in order to correctly apply the weight.
  $elements = array(
    '#type' => 'container',
    '#title' => $component['name'],
    '#title_display' => $component['extra']['title_display'] ? $component['extra']['title_display'] : 'before',
    '#weight' => $component['weight'],
    '#theme_wrappers' => array('webform_element'),
    '#webform_component' => $component,
    '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'sp_privacy') . '/css/sp_privacy.css',
      ),
    ),
  );

  $privacy_options = sp_privacy_get_options();

  $elements['privacy'] = array(
    '#type' => 'checkboxes',
    '#title' => 'Privacy voorkeuren',
    '#options' => $privacy_options,
    '#required' => FALSE,
    '#webform_component' => array('type' => $component['type'] . '_privacy') + $component,
  );

  return $elements;
}

/**
 * A hook for changing the input values before saving to the database.
 *
 * Webform expects a component to consist of a single field, or a single array
 * of fields. If you have a component that requires a deeper form tree
 * you must flatten the data into a single array using this callback
 * or by setting #parents on each field to avoid data loss and/or unexpected
 * behavior.
 *
 * Note that Webform will save the result of this function directly into the
 * database.
 *
 * @param array $component
 *   A Webform component array.
 * @param array $value
 *   The POST data associated with the user input.
 *
 * @return array
 *   An array of values to be saved into the database. Note that this should be
 *   a numerically keyed array.
 */
function _webform_submit_sp_privacy(array $component, $value) {
  foreach ($value['privacy'] as $key => $privacy) {
    $data[$key] = $privacy;
  }
  return $data;
}

/**
 * Implements _webform_display_component().
 */
function _webform_display_sp_privacy($component, $value, $format = 'html') {
  return array(
    '#title' => $component['name'],
    '#weight' => $component['weight'],
    '#theme' => 'webform_display_sp_privacy',
    '#theme_wrappers' => $format == 'html' ? array('webform_element') : array('webform_element_text'),
    '#post_render' => array('webform_element_wrapper'),
    '#component' => $component,
    '#format' => $format,
    '#value' => isset($value) ? sp_privacy_display_format($value) : '',
  );
}

/**
 * Implements _webform_theme_component().
 */
function _webform_theme_sp_privacy() {
  return array(
    'webform_display_sp_privacy' => array(
      'render element' => 'element',
    ),
  );
}

/**
 * Returns HTML for displaying the data.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 *     Properties used: #format, #value.
 *
 * @see theme_webform_element
 *
 * @ingroup themeable
 */
function theme_webform_display_sp_privacy(array $variables) {
  $element = $variables['element'];
  $value = $element['#format'] == 'html' ? $element['#value'] : check_plain($element['#value']);

  return $value !== '' ? $value : ' ';
}

/**
 * Format the data in a textual representation.
 *
 * @param string[] $value
 *   An associative array containing the data information (i.e., street name,
 *   house number, postal code and the city).
 *
 * @return string
 *   A formatted string representing the data.
 */
function sp_privacy_display_format(array $value) {
  $output = '';

  $privacy_options = sp_privacy_get_options();

  $output_tmp = '';
  $no = 1;

  foreach ($privacy_options as $key => $option) {
    if (in_array($key, $value)) {
      $output_tmp .= '<li>' . $option . '</li>';
    }
    $no++;
  }

  if (!empty($output_tmp)) {
    $output .= '<p>Privacy:<br/><ul>' . $output_tmp . '</ul>';
  }

  return $output;
}

/**
 * Implements _webform_table_component().
 */
function _webform_table_sp_privacy($component, $value) {
  $output = '';
  $privacy_options = sp_privacy_get_options();

  $output_tmp = '';
  if (!empty($value)) {
    foreach ($privacy_options as $key => $option) {
      if (in_array($key, $value)) {
        $output_tmp .= ', ' . $option;
      }
    }
  }

  if (!empty($output_tmp)) {
    $output .= $output_tmp;
  }
  return $output;
}

/**
 * Implements _webform_csv_headers_component().
 */
function _webform_csv_headers_sp_privacy($component, $export_options) {
  $header = array();

  $privacy_options = sp_privacy_get_options();
  foreach ($privacy_options as $key => $option) {
    $header[0][] = '';
    $header[1][] = '';
    $header[2][] = $option;
  }

  return $header;
}

/**
 * Implements _webform_csv_data_component().
 */
function _webform_csv_data_sp_privacy($component, $export_options, $value) {
  $return = array();

  $privacy_options = sp_privacy_get_options();

  $no = 1;
  foreach ($privacy_options as $key => $option) {
    if (in_array($key, $value)) {
      $return[] = 'x';
    }
    else {
      $return[] = '';
    }
    $no++;
  }
  return $return;
}

/**
 * Return privacy options.
 *
 * @return array
 *   Privacy options.
 */
function sp_privacy_get_options() {
  $options = array(
    //'do_not_email' => 'Niet e-mailen',
    //'do_not_mail' => 'Niet per post',
    'do_not_sms' => 'Niet sms\'en',
    'is_opt_out' => 'Niet mailen',
    'do_not_phone' => 'Niet bellen',
  );
  return $options;
}

/**
 * Implements _webform_analysis_component().
 */
function _webform_analysis_sp_privacy($component, $sids = array(), $single = FALSE, $join = NULL) {
  $privacy_options = sp_privacy_get_options();

  $option_groups = array(
    'Privacy' => $privacy_options,
  );

  foreach ($option_groups as $title => $option_group) {
    $data['table_rows'][] = array(
      '<strong>' . $title . '</strong>',
      '',
    );
    $parts = array();
    foreach ($option_group as $key => $group) {
      $parts[] = "SUM(data = '" . $key . "') AS '" . $key . "'";
    }
    $query = 'SELECT ' . implode(', ', $parts) . ' FROM webform_submitted_data WHERE nid = :nid AND cid = :cid';
    $result = db_query($query, array('nid' => $component['nid'], 'cid' => $component['cid']))->fetchAssoc();
    foreach ($result as $key => $count) {
      $data['table_rows'][] = array(
        $option_group[$key],
        $count,
      );
    }
  }

  return $data;
}
